### ISSUE TITLE
client crash (hoe+grass)

### ISSUE THREAD

**Issue by gildervine** [katubug/CozyChaos#1]
holding a hoe and destroying grass should drop a random croptopia seed, instead it crashes my client both in solo and on MP servers

version tested: 1.7.2 and 1.8.0

https://pastebin.com/mfsGKCuQ <- crashreport

**Comment by katubug** [comment]
Thank you for reporting this! I think I know what's causing the problem, and I'll try to have it fixed next update!

**Comment by gildervine** [comment]
i tested some more and what finally helped, was to simply disable in vanillatweaks the setting for 
+tweaks > "Want hoe to act like a sickle?"

**Comment by katubug** [comment]
Ooh that's excellent to know, thank you! I had assumed it was a conflict with Improved Hoes, so this helps immensely. I'll make sure the VanillaTweaks setting is off by default in the next update! Thanks again!

**Comment by gildervine** [comment]
since this is still open, ill just add some feedback here
- recipe for patchouli books : magic fungi, things and outvoted all have the same recipe and output a non-usable book
- natures compass mod : given the extra biomes in the pack, this biome compass would be a nice help for players looking to complete blaze+cave advancements

thanks for this fun pack, looking forward to more updates

**Comment by katubug** [comment]
Thank you for the feedback! I'll be putting out a new version soon to address these!

**Comment by katubug** [comment]
So the book recipes is a surprisingly difficult beast, because they are technically all the same item but with different NBT data. Datapacks don't support NBT data in crafting recipes natively, so I'd need to download a mod that enables that feature. I may do that in the future if other recipes call for NBT data. But otherwise I'm afraid I can't add a survival friendly way of obtaining the patchouli versions of the books.

I did add Nature's Compass though, that will go out with version 1.9.1 later today hopefully.

Also I'm going to close this but you're welcome to make another ticket later for feedback, I appreciate it!
